### PR TITLE
CLIC-28 Fix View Button 

### LINKED ISSUE #5: CLIC-20 Landing Page
TASK DESCRIPTION

By the end of the iteration, the landing page of the Custom Reports application should be customized to display only those features required by its users. 

HOW TO EVALUATE

Open the Odoo Custom Reports app. The user should be presented with the following:
1. In the navbar, the large "Custom Reports" text is a link to the Custom Reports landing page (current page).
2. In the navbar, a menu also titled "Custom Reports" should dropdown presenting a link to Sprint 4's custom report (probably the "Employee Performance"). 
3. In the navbar, a link titled "Configure" should take the user to a standard Odoo list view, in which the user may edit certain features of the custom reports.
4. On the page, a link for "Employee Performance" report.

Note: In order for user to view Custom Reports module, he / she might require access as a Custom Reports Manager or User. This may be activated in **Settings**.

### LINKED ISSUE #11: CLIC-28 Fix View Button
TASK DESCRIPTION

View Button does not go to URL when clicked

HOW TO EVALUATE

Open the Odoo Custom Reports app. The user should be presented with the following:

Custom Reports landing page. Each report has a VIEW button on the side. That button needs to go to the corresponding URL.

### PR DESCRIPTION
**Pull request by chang3d**

### CODE REVIEW

**Review by kevinmurphy5 — APPROVED** [review]
Merges and Works upon altering the URL as discussed.

**Comment by chang3d** [comment]
need to reopen this branch and undo the force-push from master

**Comment by chang3d** [comment]
Updated

Button now works. The URL is the ViewModel name. See the demo file.

**Review by whagan — APPROVED** [review]
Looks good. Buttons work. No conflicts with current master.

**Pull request merged**
