### PR TITLE
CLIC-36 Fix Boolean Datetime Issues

### LINKED ISSUE #36: CLIC-36 Fix Boolean Datetime Issues
For some strange reasons, a null datetime in a saved Odoo model will be treated as a Boolean by python. This may make future editing of that field problematic, as some models have functions tied to that field and it thinks it could be a Boolean that's being compared to a datetime.

Potential fixes are to set default datetimes or make them required fields.

### PR DESCRIPTION
**Pull request by chang3d**
datetime error fixed

### CODE REVIEW

**Review by whagan — CHANGES_REQUESTED** [review]
Import _ on models.

**Review by whagan — COMMENTED** [review]
Approved.

**Review by whagan — APPROVED** [review]
Approved.

**Comment by jsalajka** [comment]
Still getting the same issue - "TypeError: '<=' not supported between instances of 'bool' and 'datetime.datetime'"

**Review by kevinmurphy5 — APPROVED** [review]
Works on my machine. May work differently depending on OS or other factors.

**Pull request merged**
